[phases.setup]
nixPkgs = ["nodejs_20"]
nixLibs = []

[phases.install]
cmds = ["npm install --prefix Backend-Draftin-Clean"]

[phases.build]
cmds = []

[start]
cmd = "cd Backend-Draftin-Clean && node index.js"
