[phases.setup]
nixPkgs = ["nodejs_20"]
nixLibs = []

[phases.install]
cmds = ["cd backend && rm -rf node_modules && npm install && npm rebuild bcrypt --build-from-source"]

[phases.build]
cmds = []

[start]
cmd = "cd backend && node index.js"
