[phases.setup]
nixPkgs = ["nodejs_20", "python3"]
nixLibs = []

[phases.install]
cmds = ["cd backend && rm -rf node_modules && npm install"]

[phases.build]
cmds = []

[start]
cmd = "cd backend && node index.js"
